
name: Testes

# Gatilhos
#  Programados
#  Acionados por eventos
on:
  push:
    branches: [ main ]

jobs:
  build:
  
# Maquina ou ambiente  
    runs-on: ubuntu-latest
    
#   Passos
    steps:
    
#   Danwload do Codigo
    - uses: actions/checkout@v3
    
    
# Setup da version do Node
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
     
    - run: npm install
    - run: npm run cy:run
      continue-on-error: true
  
    - run: npm run report:merge
    - run: npm run report:mocha
    
# Github Pages --> Publicar o relatorios

    - name: Deploy to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: JamesIves/github-pages-deploy-action@8817a56e5bfec6e2b08345c81f4d422db53a2cdc
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh_pages
        FOLDER: mochawesome-report
        
      
      
      
      
      
      
      
